services:
  postgres:
    container_name: mrbs-postgres-dev
    image: postgres:latest 
    environment: 
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
volumes:
  db-data:


